### ISSUE TITLE
Remove .git folder in extension

### ISSUE THREAD

**Issue by zauni** [FluidTYPO3/fluidcontent#215]
Hello,
if I install this extension there is also a .git folder inside the typo3conf/ext/fluidcontent folder so that my projects git repository is not able to find that extension and I can not commit it. But in other extensions of you (e.g. builder) there is no .git folder and I can commit it like normal.
So is it on purpose that you left the .git folder in your extension after you upload it to TER or is it a bug?
Thanks for your time and I appreciate your hard work on this great extensions! :)

**Comment by NamelessCoder** [comment]
Hi @zauni - yes, the .git folder was accidentally uploaded in some versions of the extensions on TER and that messed a bit with people using the document root as git project. The problem is fixed, but not all extensions have been updated since then. We expect to release new versions of the remaining extensions in a couple of weeks - until then: it is 100% safe to delete those folders after installing from TER!

**Comment by zauni** [comment]
Thanks @NamelessCoder for your detailed answer.
