### ISSUE TITLE
Call to undefined method when switching to another FCE that shares some fields

### ISSUE THREAD

**Issue by Outdoorsman** [FluidTYPO3/fluidcontent#228]
*(This is all in reference to multiple column FCEs in fluidbootstraptheme, but I am guessing the errors are coming from fluidcontent, please correct me if I'm wrong. I'm using the most recent development versions of everything and the v2.0 branch of fluidbootstraptheme that's 7.x compatible.)*

**PROBLEM 1:** If I create a 4 Columns Container add content and then changed it to a 2 or 3 Columns Conainter FCE I get this error.

**PROBLEM 2:** First I create a 2 Columns Container and then add content in both columns. Then I change this FCE to a 4 Columns Container and add content to column 4. Finally I switch the FCE to a 6 Columns Container and suddenly the content element in column 4 shows up as duplicated in columns 5 and 6 in the frontend even though no content element is showing in those columns in the backend. Wierd stuff.

```Fatal error: Call to undefined method FluidCache_Fluidbootstraptheme_Content_action_index_2f34803f1c93828844f89ac8cb408a3f8189454f::section_e3c5f74a478d78c1d45c29db51ebdbae92e52cb5() in /home/some_directory/typo3_src-7.1.0/typo3/sysext/fluid/Classes/View/AbstractTemplateView.php on line 222```

**Comment by coding46** [comment]
I've tried to reconstruct your settings in a minimal version. Real simple 1-column-container, 2-column-container, 3-column-container. And played around with it in the way you describe. But none of the phenomena happened.

Then I replayed your exact version setup including the fluidbootstraptheme thing (v2.0 and so on) and the only thing I can confirm is the 6-column thingie with those tripled columns 4,5, and 6. But this is caused by a bug in the 6-column template of fluidbootstraptheme, where you'll find the following code:

```
<div class="{settings.grid6.col4width} {settings.grid6.col4CSS} {f:if(condition: settings.grid6.eqh, then: 'equal-height')} {f:if(condition: settings.grid6.col4hide, then: 'hidden-xs')}">
	<flux:content.render area="column4" />
</div>
<div class="{settings.grid6.col5width} {settings.grid6.col5CSS} {f:if(condition: settings.grid6.eqh, then: 'equal-height')} {f:if(condition: settings.grid6.col5hide, then: 'hidden-xs')}">
	<flux:content.render area="column4" />
</div>
<div class="{settings.grid6.col6width} {settings.grid6.col6CSS} {f:if(condition: settings.grid6.eqh, then: 'equal-height')} {f:if(condition: settings.grid6.col6hide, then: 'hidden-xs')}">
	<flux:content.render area="column4" />
</div>
```
Yes, column 4 gets rendered 3 times. ;)

So the fatal seems to be a cache thing on your side and for the frontend stuff the fluidbootstraptheme is to be blamed. :D

Who needs 6 columns anyway?

**Comment by Outdoorsman** [comment]
Apparently clearing all 3 caches from the backend or install tool wasn't enough. I did an ```rm -rf typo3temp/*``` and it seems that those cache issues went away.  I just submitted a PR for the other fluidbootstraptheme bug. This issue seems to be resolved... thanks for the detective work.
