### ISSUE TITLE
Template could not be loaded error after upgrading from typo3 7.2 to 7.4

### ISSUE THREAD

**Issue by vinayn** [FluidTYPO3/fluidcontent#268]
I am getting the following error after upgrading from typo3 7.2 to 7.4

**Template could not be loaded. I tried "typo3conf/ext/fluidcontent/Resources/Private/Templates/Content/Index.html", "/typo3conf/ext/fluidcontent/Resources/Private/Templates/Content/index.html"**

I have cleared cache using install tool and manually as well. I am using windows 7 and php 5.6.3

flux   - 7.2.1 
fluidpages - 3.3.1 
fluidcontent - 4.3.1

**Comment by xf-** [comment]
I think you have no template selected in Page Layout.
-> Edit Page and select on (this is the default fallback)

**Comment by vinayn** [comment]
after upgrading typo3 from 7.2 to 7.4 the columns  tx_flux_column,tx_flux_parent ,tx_flux_children  and tx_fed_fcefile don't have data . The columns tx_flux_column,tx_flux_parent and tx_flux_children are having 'null' value. I had to move the data manually from 7.2 DB of typo3

**Comment by NamelessCoder** [comment]
I can only guess, but I think what may have happened is that you maybe uninstalled the extensions during the upgrade, then ran the install tool to compare DB schema *and allowed it to rename or remove deleted fields*. Which then caused the fields to be re-added when you reinstalled the flux etc. extensions - but as empty fields (and EM is not able to detect the old fields renamed with `zzz_` and restore them).

Or you simply used a deprecated syntax for defining your template root paths, e.g. used `templateRootPath` instead of `templateRootPaths.10` and so on.

Either way, thanks for updating the issue about the solution! Hopefully your info plus the info I gave above, will help someone else solve any similar problems :)
