### ISSUE TITLE
No icon in backend for content-elements

### ISSUE THREAD

**Issue by papillon6** [FluidTYPO3/fluidcontent#272]
URL for backend icon is not correct. If no icon is specified in options at all then this path is rendered in backend (content-element-wizard):
![fluidcontent_no-image](https://cloud.githubusercontent.com/assets/10079852/9471961/00703ed0-4b53-11e5-90f0-467625408a8d.PNG)

This code
```
<flux:form options="{icon: 'typo3conf/ext/myext/Resources/Public/Icons/icon.png'} ..."/>
```
renders to:
![image](https://cloud.githubusercontent.com/assets/10079852/9472165/e0809a24-4b53-11e5-9e46-1a3953f77116.png)

...which is actually http://domain.de/typo3/typo3conf/ext/myext/...

Trying to "eleminate" the "typo3" in this path by using a relative path like this:
```
<flux:form options="{icon: '../typo3conf/ext/myext/Resources/Public/Icons/icon.png'} ..."/> 
```
leads to:
![image](https://cloud.githubusercontent.com/assets/10079852/9472239/52941816-4b54-11e5-8f55-ff1fefe0599d.png)

Any viewhelpers needed here!?

Further information:
fluidcontent 4.3.1 (TER)
TYPO3 6.2.14

**Comment by ervaude** [comment]
I stumpled over missinf FCE Icons as well. There was a change in the way those icons are generated. Sadly the new generation depends on a new method within the flux extension itself. This method is not included in any release but only in the development branch. So if you need those icons you can downgrade fluidcontent to have the old way of generating icons or you can switch from the latest release to the develop branch of flux (that is what I do currently) or you just wait for a release of flux that contains the new method.

BTW there is a check if the new method exists in fluid, but the path to the icon is manipulated before, so its not working when the check fails, which is in my opinion the actual bug here. The DC is failing.

**Comment by xf-** [comment]
Confirmed - the realpath tool should be inside Condition "if createIcon is available"

**Comment by NamelessCoder** [comment]
If what @xf- reports is all that is required for fixing this, then it's fixed :)

Thanks for reporting guys! Please test with newly released `fluidcontent` when you get the chance.

**Comment by julianxhokaxhiu** [comment]
Well...I'm using Flux development branch (latest commit) + FluidContent 4.3.2 from TER and is still not working. Any suggestions?

![fail](https://cloud.githubusercontent.com/assets/1237070/9813348/022aebbe-5885-11e5-977b-8b0d4c959eda.png)

**Comment by Ghaniball** [comment]
@NamelessCoder, the changes in \FluidTYPO3\Flux\Utility\MiscellaneousUtility::getIconForTemplate in flux:7.2.2 broke again this method \FluidTYPO3\Fluidcontent\Service\ConfigurationService::buildWizardTabItem

**Comment by papillon6** [comment]
In the wizard-tab the icons are shown, but in module web -> page the small icon in front of any fluidcontent-element is still missing... the image-uri is still wrong:

/typo3/sysext/cms/typo3conf/ext/...

**Comment by Kitzberger** [comment]
@papillon6 : see issue #361
