### ISSUE TITLE
System categories for content-elements.

### ISSUE THREAD

**Issue by rotespferd** [FluidTYPO3/fluidcontent#286]
I can not set system categories ([Documentation](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Categories/Index.html)) for elements created with Fluidcontent.
The table tt_content is categorizable by default, so every content-element could have categories.

Why is this not possible with content-elements from fluidcontent?

**Comment by NamelessCoder** [comment]
Hi Martin,

This is done as *opt-in*, in order to avoid pushing category fields onto every single Fluidcontent element type. You can reintroduce this field by changing the TCA of the `fluidcontent_content` type so that the `categories` field is included in `showitem`. If you then wish, you can also add a `displayCond` to the `categories` field so it only gets shown if `CType` is either not `fluidcontent_content` or `CType` is `fluidcontent_content` *and* `tx_fed_fcefile` is whichever value you want to target.

See TYPO3 documentation for further information about how to work with TCA. Although it's quite outside the scope of FluidTYPO3, learning this is still highly recommended as it also allows you to do similar changes for *any* extension's fields.

**Comment by rotespferd** [comment]
Thank you for this hint and your help.

In order to understand this properly:
I need to add the ```categories``` field via the TCA. So I add it to the array ````$GLOBALS['TCA']['tt_content']['types']['fluidcontent_content']['showitem']````?

**Comment by NamelessCoder** [comment]
Correct, with one minor exception - "showItems" is a long string of CSV field names with a special syntax allowing things like sheet names to be defined as well. The lazy solution is to just `.= ',my_fieldname';` to that string, but normally you want to place it somewhere relative to another field, in a custom sheet etc. and that's where you have a collection of API methods to manipulate the TCA.

I hesitate to offer any concrete examples because you really should study the appropriate documentation instead of only using what I echo - there are dozens of different ways you can manipulate these configuration arrays/strings.
