### ISSUE TITLE
New content element wizard: Automatically select if there is only one element

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidcontent#299]
I've got a container element with a grid column that allows only a single type of elements.

Currently I click on "(+) Content", then have to click on the only content element type that's allowed before I can fill the content element's fields:
![2015-11-05 typo3 new content element single](https://cloud.githubusercontent.com/assets/59036/10965129/407e6110-83ab-11e5-8a17-5d8313681af0.png)

It would be much nicer that the "new content element" wizard would automatically select the only available element, so that the editor does not have to select the content element at all.

Example code that limits a grid column to a single element: http://p.cweiske.de/233

```
<flux:grid.column name="left"
 variables="{allowedContentTypes: 'fluidcontent_content', Fluidcontent: {allowedContentTypes: 'Vendor.VendorFluidTest:Teammember.html'}}"
 />
```

This follows commit 5d63b574fa84564896c4dd3b198523508d21f9d4, which implemented the FCE whitelist.

**Comment by jmverges** [comment]
Hello @cweiske,

Usually I like this kind of features but I think we shouldn't change the behaviour by default.

 I could agree with you in the fact you can "save" one click to the user. However I really think this is not related with fluidcontent because at the end this is to change a behavior. 

You could create your own extension extending Wizard somehow and then tell to Wizard: "if you only find 1 element just skip the wizard an proceed" 

If you decide to create such extension, please let me know ;)

**Comment by cweiske** [comment]
I've opened a bug for TYPO3 core: [Feature #71365: New content element wizard: Automatically select if only one item available](https://forge.typo3.org/issues/71365)

**Comment by NamelessCoder** [comment]
Those of you that have typo3.org accounts feel free to add your "I'm with Christian" votes on the linked issue - I agree this would be a nice streamlining change.
