### ISSUE TITLE
TYPO3 backend broken when FCE is broken

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidcontent#315]
I'm during development, creating a content element that uses a custom view helper (which is not written yet).

With saving the `contentelement.html`, the TYPO3 backend is not usable anymore because

> #1289386765: Could not analyse class: Vendor\Extname\ViewHelpers\SomeViewHelper maybe not loaded or no autoloader?

Why is this file parsed, even if i'm only loading the main backend frameset, the page tree or a page's the list view?

It should not be so easy to break the whole system.

**Comment by NamelessCoder** [comment]
If you are in Development context then yes, it should be that easy to break the system because the setup obviously contains an error that's relevant to know about for developers ;)

The file gets parsed because the template gets processed to retrieve the Form instance configured within it. Fluid does this by parsing the *entire* file rather than just the section, which means you'll receive exceptions like these which are formally correct.

The error in question corresponds to using a non-existent PHP class in delivering a data structure that gets used by the element. It's every bit as fatal as that and I don't think we should start catching these. Once we do, a LONG path of decision after decision and custom handling will ensue, arguing which errors should be considered friendly and which shouldn't - for example, anything caused by FAL inside a template, problems with missing TS settings that are referenced, invalid argument usages for ViewHelpers, non-existing Partials, and so on with every single type of exception that could possibly be thrown by parsing a Fluid template.

Knowing this I'm not sure what you will think about the suggestion to suppress such errors. Wouldn't you rather agree that something like that - using a class that doesn't exist or is in a namespace that isn't registered - is indeed a fatal error you must know about and fix to restore your backend, given that you actually have an instance of the element in question being used on the page that then breaks?

**Comment by cweiske** [comment]
Why are this files parsed at all when I e.g. "only" load typo3's main frame view, or the page tree?

**Comment by NamelessCoder** [comment]
When the parsing happens depends on the current state of your caches among other things, but even with those cached, the template file in question gets parsed because:

* You've got an instance of the element associated with the template.
* We read the Form instance from that template to know things like the icon, enabled state, etc. (icon cached, enabled state cached but NOT in selectors, only pageTSconfig)
* Things like the page module render Previews from the template (gets compiled if possible).
* List view tries to render the custom icon from the template (gets cached).

So depending on cache status, either one of these needs a valid template file in order to function. As expressed, the only way to suppress this is to suppress exceptions - and this is not a direction I think we should take.

**Comment by NamelessCoder** [comment]
Oh and the template is obviously also parsed if you perform any operation on the element that references the invalid template - the Providers will try to access it to read a Grid, among other things.

**Comment by cweiske** [comment]
My guess for the crash when loading the typo3 backend itself would be that typoscript is generated for the new content element wizard, even if it's not used at all at this stage. This is probably hard to work around.

**Comment by cweiske** [comment]
Today a user in the #fedext channel told us that he couldn't even login to the backend after copying his local dev files to live:

> Uncaught TYPO3 Exception
> GuestOfToday #1225709595: Template could not be loaded. I tried "/is/htdocs/wp12479957_J4K1BCWXFP/www/typo3conf/ext/template/Resources/Private/Templates/Page/Render.html"

This is the same base issue.
