### ISSUE TITLE
Resorting of Section Objects doesn't respect the content in it

### ISSUE THREAD

**Issue by andyhausmann** [FluidTYPO3/fluidcontent#319]
If I have an accordion object and want to move the first object to another position, the child content doesn't move as well.

For example:

Accordion 1, Content 1
Accordion 2, Content 2
Accordion 3, Content 3

After switching Accordion 1 with 3, it results like follows:

Accordion 3, Content 1
Accordion 2, Content 2
Accordion 1, Content 3

As you can see, the content remains with a wrong relation in this case. My customer has an Accordion containing Job proposals. If a new proposal comes in, they want to adjust the sorting.

Maybe this is a not intended behavior. What do you think?

**Comment by NamelessCoder** [comment]
Hi Andy,

This is (unfortunately, one might argue) expected behavior when the only input identification is the index in the array. To combat this, FluidTYPO3 adds a custom object ID (invisible/uneditable property called `id` on each object in the section) automatically when you save objects. Using *this* ID as `name` of your `flux:grid.column` nodes will cause the content to "move" along with the section object (because the object retains its unique ID when moved). You *can* also implement this field as actually editable, so that editor can define the expected name of the column - but changing the value causes problems unless you know what you're doing.

Hope this explains the logic as well as how to work around it ;)

PS: for this type of setup I normally advise making each job proposal either a page or a content element, depending on what you need to be able to enter into it. The page way usually works best; lists can be made with `v:page.menu` and it's family members, they get indexed individually, have a straight-forward and unique URL and can be sorted, hidden, time-restricted, access protected, ...
