### ISSUE TITLE
Using the f:translate ViewHelper does not work in version 4.3.x

### ISSUE THREAD

**Issue by JostBaron** [FluidTYPO3/fluidcontent#324]
My flexform definitions look like this:

    <f:section name="Configuration">
        <flux:form
                id="text"
                label="{f:translate(id: 'text.name')}"
                description="{f:translate(id: 'text.description')}"
                options="{
                    group:  '{f:translate(id: \\'text.tabname\\')}',
                    icon: '{v:extension.path.resources(path: \\'Icons/contentelement.png\\')}'
                }">

            <flux:field.text
                name="text"
                label="{f:translate(id: 'text.text.label')}"
                enableRichText="1"
            />
        </flux:form>
    </f:section>

In versions up to 4.2.4, this works fine, but in versions 4.3.x the labels are not translated, they are shown in the default language. Could not check the behavior in version 4.4.0, because I have not 7.x installation running to do so.

**Comment by NamelessCoder** [comment]
Hi Jost,

This is sort of by design. Actually it's a side effect of added caching combined with slightly off-standard LLL use. The reason is that you translate the labels at the time of rendering the template and this output then gets cached with translated values. To avoid that you have two options:

* Don't specify the `label` at all and rely on Flux's automatic LLL references that are created.
* Specify labels as `LLL:EXT:...` paths which TYPO3 can translate internally; TYPO3 will then perform translations on the cached configurations.

It's usually easiest to avoid the "label" attribute completely and let Flux build the expected label IDs. Then all you need to do is place those in your LLL and the rest happens behind the scenes.

**Comment by JostBaron** [comment]
Hmm, not funny. That's about 1 or 2k labels I've got to adapt. Can't you just build in a solution that does not rely on some convention, but allows to define my own label ids? Reasons:

 * When moving a field to another place in the form, the label id changes.
 * When putting a field in a partial, the label ID depends on the position where the partial is used.
 * Backwards compatibility

My idea would be to add an attribute `label-id` to all elements having a label, and then using that for fetching labels (with label name be convention as fallback of course).

**Comment by NamelessCoder** [comment]
> My idea would be to add an attribute label-id to all elements having a label, and then using that for fetching labels (with label name be convention as fallback of course).

There is one thing you can do for this that I forgot to include - using the format `LLL:keyname` internally expands that to the full `LLL:EXT:key/....` format. That only works for the actual label though, but it does work for any field that has a label. And it avoids both issues you describe - so we kind of already have that `label-id` feature.

For the other fields you will need some search-and-replace to turn those references into `LLL:EXT:....` paths - sorry. On the positive side your backend performance will be better not just for skipping some double translation calls but also because the pageTSconfig can be cached at all now.

If all else fails: override the cache backend for the `fluidcontent` cache to use a TransientMemoryBackend or similar so it won't persist the state between users.
