### ISSUE TITLE
flux.form wizardTab="GroupName" or options="{group: 'GroupName'} - in non-latin characters ?

### ISSUE THREAD

**Issue by konstantin83** [FluidTYPO3/fluidcontent#327]
Hello.
No content element is displayed and no tab is created when I give a tab name in non-latin characters, for example in Cyrillic:
`<flux:form id="Text" options="{group: 'Основное'}" label="Текст с картинкой">`
Label by the way works just fine.
The only solution is to set any number or any latin character before cyrillic like this for example:
`<flux:form id="Text" options="{group: '1-Основное'}" label="Текст с картинкой">`

Can this be fixed?

**Comment by NamelessCoder** [comment]
Hi Konstantin,

I'm not sure this is fixable or at least easily fixable - the group name gets used as key names in the new content wizard (that's how the wizard logically groups - example: `foo_first` and `foo_second` would be the key names caused by using `foo` as group name and having `First.html` and `Second.html` as content templates). Unfortunately TYPO3 (still) needs this slightly esoteric method and there's nothing we can do in this case since we have to deliver the setup as a TypoScript compatible array with some extra rules on top regarding naming of each key. So it would be those rules/restrictions you would need to target instead.

It *might* be possible to convince the TYPO3 contributors to accept a patch that relaxes this a bit, for example to allow any UTF-8 as key name in the new content wizard's items (and such allow any UTF-8 as group *and* as template file name). But I fear it's a general restriction of TypoScript itself that would only be possible to implement if it was implemented for TypoScript in general, which certainly makes it a lot more complicated to achieve (would not be a simple matter of changing the wizard; TS parsing itself would need to be changed).

If you decide to open an issue about this in the TYPO3 core bug tracker (I guess it would have to be a feature request) I'd be happy to vote for it but unfortunately I don't have time to create the patch myself.

**Comment by konstantin83** [comment]
Thanks for your feedback. I will open an issue in the Typo3 core bug tracker, as you adviced. )

**Comment by NamelessCoder** [comment]
Hi Konstantin,

I may have spoken too soon on this one. Please try:

1. Use a standard `latin1` name for the group, like `main`.
2. Add a new LLL entry in your provider extension's XLF file(s): `fluidcontent.newContentWizard.group.main`.
3. Flush system cache (it's important that it is the system cache you flush; that is where LLL gets cached).

This should allow you to use the special names, but has a downside due to the current translation behaviors of Flux and Fluidcontent (which will be fixed in a while) - the downside is that the configuration gets cached in the language you first view it in (does not change according to backend users' language).

You can probably close the core issue - although the problem I described still does exist, you can and should work around it using this LLL approach (just like Mattes says in the core issue). Sorry for the confusion - I had simply forgotten all about this special LLL name we support!

**Comment by konstantin83** [comment]
Thank you for such much attention to this issue. I have read the Mattes' answer on core issue - I think that group label behavior should be used without LLL. Because we use "label" without it - just a simple string in any language. This issue in my opinion should be resolved by core team to simplify group naming.
