### ISSUE TITLE
Disable tabs/icons in the new content element wizard

### ISSUE THREAD

**Issue by SomeBdyElse** [FluidTYPO3/fluidcontent#333]
As a developer, I would like to be able to disable the new content element wizard tabs/items that fluidcontent produces: 

Background: 
I use my own PageTSConfig file that customizes the new content element wizard dependent on the page type. The PageTSConfig fluidcontent modifies the show list of the new content element wizard tabs at a very late stage. Therefore I cannot override/influence the changes. 

Possible solutions: 
* Add "hide in new content element wizard" to the options array passed to the form view helper. 
* Add a configuration option to disable the new content element wizard additions altogether.

**Comment by SomeBdyElse** [comment]
Right now, I use the following line in ext_localconf.php: 

`unset($GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['GLOBAL']['extTablesInclusion-PostProcessing']['fluidcontent']);`

**Comment by NamelessCoder** [comment]
Hi Hannes,

Your `unset()` example would be exactly the approach I recommend for not just this, but any other extension which adds hooks the functionality of which you manually reproduce. You probably also want to unset `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['cms']['db_new_content_el']['wizardItemsHook']['fluidcontent']` and/or `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_userauthgroup.php']['fetchGroups_postProcessing']['fluidcontent']` depending on whether or not you want the ACL manipulations to be performed.

The alternative to the above would be:

* Extension configuration options for fluidcontent where currently there are none (requiring documentation)
* Performance drain because every request would need to load and unserialize such options
* A condition that executes for every user for every request in perpetuity

As it is, I have to reject this feature request - you are already capable of doing exactly what you need to do, in a way that works not just for fluidcontent but for everything else, and which would not affect any other user whatsoever, nor require any maintenance or documentation on our part. It is, in not so many words, a TYPO3 core feature that you can change these arrays to get the result you want ;)

PS: you may also find the "Configuration" backend module useful as it allows administrators to change said configuration without editing PHP.

**Comment by SomeBdyElse** [comment]
OK, thanks (really) for the long reply! 

I did not like the unset solution, because it disables the entire extTables post processing and I was not aware, whether that includes anything else but the new content element wizard code. Yet, I have not seen any unwanted side effects so far, so I am happy to consider this closed.

**Comment by NamelessCoder** [comment]
The hook in question has a single responsibility - to generate the cached pageTSconfig that is then used by the new wizard items hook. Disabling either one causes fluidcontent to not generate any cached config or not apply any cached config, respectively. You won't affect other extensions' hooks by unsetting, as long as you target the `fluidcontent` array index (which was by the way named `fluidcontent` intentionally exactly to allow targeting it this way; as opposed to just `[]`'ing a value onto the end).

**Comment by SomeBdyElse** [comment]
Just a remark: 

If I remove the fluidcontent hook from $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_userauthgroup.php']['fetchGroups_postProcessing']['fluidcontent'], editors can not add or edit fluidcontent elements any more. 

```
unset($GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['GLOBAL']['extTablesInclusion-PostProcessing']['fluidcontent']);
unset($GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['cms']['db_new_content_el']['wizardItemsHook']['fluidcontent']);

# the offending line
unset($GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_userauthgroup.php']['fetchGroups_postProcessing']['fluidcontent']);
```

If editors (non-admins) access a TCE form to edit or create a fluidcontent element, an exception is thrown: 

```
#1: PHP Catchable Fatal Error: Argument 1 passed to FluidTYPO3\Fluidcontent\Backend\ContentTypeFilter::filterByBlacklistAndWhitelist() must be of the type array, null given, called in XXX/Web/typo3conf/ext/fluidcontent/Classes/Backend/ContentTypeFilter.php on line 85 and defined in XXX/Web/typo3conf/ext/fluidcontent/Classes/Backend/ContentTypeFilter.php line 93
```

Without the last line, everything seems to work as intended.
