### ISSUE TITLE
fluidcontent won't work with bootstrap_package 

### ISSUE THREAD

**Issue by vinayn** [FluidTYPO3/fluidcontent#338]
The default template "Example.html" generated using builder extension is working fine. Any additional templates added with sheet and object won't show any output after selecting the fluid content  template(while adding content). The builder command builder:fluidsyntax won't show any issue. After disabling bootstrap_package extension everything is working as expected . I am using typo3 7.6.2.

**Comment by NamelessCoder** [comment]
Could be a problem with the template (unexpected Layout name, typo in section name/names, condition not matching correctly and suppressing output, etc) but could also be caused by one or more hooks introduced by `bootstrap_package` to achieve certain functions. I'm not aware of what the situation might be with that.

Logical (non-syntax) errors in templates will not be reported by checking the syntax with the `builder` extension but at least we can say that your template *syntax* is valid.

I would check if the very same template works *without* `bootstrap_package`. If it works without it, you can report the incompatibility to the `bootstrap_package` issue tracker and maybe they can achieve compatibility (since `bootstrap_package` chooses to replace the content rendering instructions completely that may be a challenge) or declare a conflict in the `bootstrap_package` manifest. If it also doesn't work without `bootstrap_package` you can be fairly sure it's a logical error in the template itself.

The official word from our side would be that nothing whatsoever in neither `fluidcontent` nor `flux` should conflict with any content rendering instructions which comply with TYPO3 standards. If the TYPO3 site can render generic (Extbase) plugins it can render `fluidcontent` - generally speaking, of course. All we require is a working plugin rendering instruction and it could come from anywhere; `css_styled_content`, `fluid_styled_content`, `fluidcontent_core` or `bootstrap_package` - but it is the responsibility of such packages to provide working integration for Extbase plugins, which sometimes requires special efforts like https://github.com/NamelessCoder/fluidcontent_core/blob/development/Classes/Service/UpdateService.php#L89
