### ISSUE TITLE
Backend gets too slow with fluidcontent extension in case of many pages 2

### ISSUE THREAD

**Issue by aboritskiy** [FluidTYPO3/fluidcontent#344]
Hi FluidTYPO3 team, we were struggling with the same issue as described in https://github.com/FluidTYPO3/fluidcontent/pull/335 

[Here](https://github.com/FluidTYPO3/fluidcontent/compare/0cb0e06...sitewards:wizard-tabs-caching-4.3.3) is the fix based on version `4.3.3`, we use that version because we are working on Typo3 v `6.2.19` at the moment and can not upgrade to later version due to compatibility issues. I can not create a pull-request directly to a commit, therefore I'd like to ask your help here - could you setup a branch based on `4.3.3`, my changes can also be merged to development branch, but I'd like them to be back ported to 4.3.x as well, happy to provide more information here.

**Comment by NamelessCoder** [comment]
Hi Anton,

You can create a pull request based on and directed to the `legacy` branch on the repository, but I strongly suggest you back-port https://github.com/FluidTYPO3/fluidcontent/commit/e945a1d36eab1d1a93737761c6dbd4594435b058 instead of adding new methods - this will make it a lot easier for any patches for this same code coming after this one.

The `legacy` branch is not up-to-date with 4.3.3 but if that version also works on 6.2 (I did not check) we'd be happy to receive a pull request to merge tag 4.3.3 into branch `legacy` (and you can then start your patch from that branch as well as use that branch in your production and receive fixes others may push).

The approach is the same for our other repositories - and if you come across a repository that doesn't have a legacy branch, request one in an issue like this one and we'll create it so it can be PR'ed into.

**Comment by fedir** [comment]
@aboritskiy Thx for the patch, worked great on fluidcontent v.4.4.1 & TYPO3 7.6 installation ! Much better performance of the backend.
