### ISSUE TITLE
[BUG] fluid_styled_content and f:cObject lib.stdheader

### ISSUE THREAD

**Issue by ste101** [FluidTYPO3/fluidcontent#354]
I tried fluid_styled_content.
Rendering the header via ```<f:cObject data="{record}" typoscriptObjectPath="lib.stdheader" />``` works.
But this line sets ```{v:content.resources.fal(field: 'bild')}``` to 'NULL'.
Using ```<f:cObject>``` after ```{v:content.resource.fal}``` works.
You will find an example file attached.
[TextBild.html.txt](https://github.com/FluidTYPO3/fluidcontent/files/295289/TextBild.html.txt)

**Comment by NamelessCoder** [comment]
This should be reported as a flaw in `f:cObject` (which belongs in the TYPO3 core). It is possible that this ViewHelper overrides and does not restore one or more global parameters; such as the content object data that's stored in ConfigurationManager. This could be happening in `f:cObject` itself or anywhere in any of the objects you used in `lib.stdheader`.

But it is definitely not related to `fluidcontent` and not caused by VHS either - generally speaking, if a third-party ViewHelper breaks some VHS ViewHelper, please report that problem where that third party ViewHelper comes from, because that's where it needs to be fixed/prevented.

**Comment by ste101** [comment]
I created a bug report in forge:
https://forge.typo3.org/issues/76489
Maybe someone could descripe it better.
