### ISSUE TITLE
Installation fails due to non-existing cache "fluidcontent"

### ISSUE THREAD

**Issue by dneuge** [FluidTYPO3/fluidcontent#355]
When installing `fluidcontent`, BE shows an error page for current development branch:

> Oops, an error occurred!
> A cache with identifier "fluidcontent" does not exist.

Another call to the extension manager (or any other BE page) shows yet another error message:

> $hookObject "FluidTYPO3\Fluidcontent\Backend\TableConfigurationPostProcessor" must implement interface TYPO3\CMS\Core\Database\TableConfigurationPostProcessingHookInterface

Upon deleting all files from `typo3temp` (using `find typo3temp -type f -delete`), BE works again and the extension shows as installed.

However, attempting to save any FCE fails with:

> 2: SQL error: 'Unknown column 'tx_fed_fcefile' in 'field list'' (tt_content:NEW5763df148a4e3448150824)

Apparently, the exception caused an incomplete installation by preventing proper handling of at least `ext_tables.sql` which defines `tx_fed_fcefile`.

The cause is the newly introduced caching of PageTSConfig in `ConfigurationService::getPageTsConfig()` which calls `getCache('fluidcontent')` without checking for existance first. That cache appears to be missing during installation; according to the Core API documentation `getCache` then fails with `NoSuchCacheException	`.

We've fixed the issue by checking for cache availability before use; pull request following shortly.

**Comment by NamelessCoder** [comment]
Hi Daniel,

I think at this point it's due time for a refactoring of code that generates this pageTSconfig so that it silently will operate both if there is no cache or the cache is disabled or removed. I appreciate your contribution but will create a separate patch to include the refactoring and use try/catch to always return a working result also when cache is inoperable.

By the way: this is the first time I've seen the message about the invalid hook object be related to this other issue - I don't know if they are directly related but if so, making the pageTSconfig fetching more resilient and predictable should prevent that issue. Sorry to hijack the issue but I saw a significant need to improve some of my own earlier messes ;)

**Comment by dneuge** [comment]
I was thinking about try/catch vs. calling `hasCache` as well but `hasCache` seemed like the cleaner solution to figuring out if the cache is available or not.

In the meantime I've fixed the issues found by CI so it shows green. Maybe you would still like to merge the PR to fix the immediate issue until you find time for the rewrite?

I've missed that there are unit tests in this project. I've now split the old test case `onlyFetchRootTypoScriptOfRootlineIfTheFluxConfigurationManagerIsInjected` into 3 parts (cached, not cached, cache unavailable) and renamed it to better reflect what it's actually checking. If the old implementation would stay around there are also test cases missing to verify the for-loop merging zero, one or many responses and ignoring previously processed ones.
