### ISSUE TITLE
Warning! Fluid Content type not selected - on new unsaved element

### ISSUE THREAD

**Issue by Mumpitz** [FluidTYPO3/fluidcontent#392]
I am using Typo3 8.6.0, fluidcontent 5.0.0, fluidpages, 4.0.0, flux 8.0.2 and vhs 4.0.0.

When i create a new Fluid Content Element in the Backen, the Warning _"Fluid Content type not selected - edit this element to fix this!"_ appears in the Plugin Options Section, although the Fluid Content Type Dropdown already shows the correct Type selected.

After saving, the Options of that element Type show up correctly and the Element can be used as expected.

**Comment by NamelessCoder** [comment]
Hi @Mumpitz - is it possible that you have some TCA override in another extension which is causing https://github.com/FluidTYPO3/fluidcontent/blob/development/Configuration/TCA/Overrides/tt_content.php#L39 to be overwritten? This setting should mean that the `tx_fed_fcefile` value will be allowed as "defValues" in the URL.

Side note, if you disable the new content element wizard this also happens because you then have to first select `Fluidcontent` from the content type selector, then a Fluidcontent type from the `Fluid content type` selector. Between those two actions the warning will also be displayed and this is expected.

**Comment by Mumpitz** [comment]
I've checked my fluidcontent extension. This line is missing in my tt_content.php, although i had the extension installed trough the Extension Manager. The file is smaller at all.
https://gist.github.com/Mumpitz/c2600afd9319efca13e7be9d6558a1f0

After adding this Line, i can see the Plugin Options right from the beginning.
Went something wrong with my installation?

**Comment by NamelessCoder** [comment]
Indeed - this will be included in the next TER release. Good to know :)

It's not a problem with your installation as such, just a missing config option that is now correctly enforced.
