### ISSUE TITLE
fluidcontent 5.0.0 fails on typo3 7.6 with php5.6 because of php7 syntax "??" in ConfigurationService.php

### ISSUE THREAD

**Issue by meganoth** [FluidTYPO3/fluidcontent#417]
typo7.6 still supports php5.6, but fluidcontent 5.0.0 has a line with php 7 syntax, i.e. the operator "??"  
Fluidcontent 5.0.0 is available now for install through TES, but hangs the UI of typo3 7.6 if you try to install it on a machine with php5.6. 

The problematic syntax is in line 312 of Classes/Service/ConfigurationService.php

**Comment by NamelessCoder** [comment]
Fluidcontent 5.0 is when we started requiring PHP 7+ so that's to be expected. See https://github.com/FluidTYPO3/fluidcontent/blob/5.0.0/composer.json#L7 - this is also declared in the TER configuration file - https://github.com/FluidTYPO3/fluidcontent/blob/5.0.0/ext_emconf.php#L26 - so TYPO3 shouldn't have allowed you to install this particular version.

You may want to report this to the TYPO3 core issue tracker as a possible issue with either TER or the extension manager, at https://forge.typo3.org/projects/typo3cms-core.
